#
###################################
# Site wide configuration
####################################
#
title: Tung D. Le
email: tungld@gmail.com
description: Tung D. Le's homapage
url: https://tungld.github.io
keywords: ["blog", "research", "tung", "tungld"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Tokyo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Tung D. Le
  avatar: tungld.png
  job: "Researcher"
  bio: "A wander among high performance computing, programming languages, and deep learning."
  email: 'tungld@gmail.com,tung@jp.ibm.com'
  disqus-shortname:
  twitter: tungld
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: tungld
  linkedin: tungld
  skype: le-duc-tung